### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by paradauer** [OE7DIO/rasp_sensor#3]
Mia miasn endlich auf Websocket umstelln

**Comment by alessacher** [comment]
I don't work on this project. I'm only here to review the code. Don't assign me to anything!

**Comment by paradauer** [comment]
AAAAAAAAA Herr Lessacher, bei Ihrer Arbeitsmoral woas i nit, wie lang i sie no in da Firma behalten kann!

**Comment by paradauer** [comment]
Es lafft so halb, übertragung steht, aba no nit mit msgpack
